In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import vgg19
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.models import Model

# Load the content and style images
content_image_path = 'mountain.jpg'
style_image_path = 'starrynight.jpg'

# Image preprocessing and deprocessing utilities
def preprocess_image(image_path):
    img = load_img(image_path, target_size=(224, 224))
    img = img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = vgg19.preprocess_input(img)
    return tf.convert_to_tensor(img)

def deprocess_image(x):
    x[:, :, 0] += 103.939
    x[:, :, 1] += 116.779
    x[:, :, 2] += 123.68
    x = x[:, :, ::-1]
    x = np.clip(x, 0, 255).astype('uint8')
    return x

# Define content and style layers
content_layers = ['block5_conv2']
style_layers = ['block1_conv1', 'block2_conv1', 'block3_conv1', 'block4_conv1', 'block5_conv1']

# Load VGG19 model
model = vgg19.VGG19(weights='imagenet', include_top=False)

# Get feature extractors
content_model = Model(inputs=model.input, outputs=[model.get_layer(layer).output for layer in content_layers])
style_model = Model(inputs=model.input, outputs=[model.get_layer(layer).output for layer in style_layers])

# Get content and style features
content_image_features = content_model(preprocess_image(content_image_path))
style_image_features = style_model(preprocess_image(style_image_path))

# ... Rest of the style transfer code . 




ValueError: Found unexpected instance while processing input tensors for keras functional model. Expecting KerasTensor which is from tf.keras.Input() or output from keras layer call(). Got: [[[[  55.060997    15.221001    48.32     ]
   [  57.060997    17.221       50.32     ]
   [  56.060997    16.221       52.32     ]
   ...
   [  12.060997   -22.779       12.32     ]
   [  13.060997   -24.779       12.32     ]
   [  13.060997   -23.779       11.32     ]]

  [[  56.060997    19.221       54.32     ]
   [  56.060997    19.221       54.32     ]
   [  53.060997    17.221       54.32     ]
   ...
   [  13.060997   -26.779        9.32     ]
   [  10.060997   -29.779        2.3199997]
   [   9.060997   -30.779        1.3199997]]

  [[  53.060997    20.221       56.32     ]
   [  54.060997    21.221       57.32     ]
   [  55.060997    22.221       58.32     ]
   ...
   [   9.060997   -30.779        2.3199997]
   [   9.060997   -33.779       -5.6800003]
   [   7.060997   -35.779       -7.6800003]]

  ...

  [[  26.060997   -24.779     -123.68     ]
   [ 148.061       68.221      -31.68     ]
   [ 130.061       44.221      -76.68     ]
   ...
   [ -65.939      -21.779     -123.68     ]
   [ -42.939003   -14.778999  -123.68     ]
   [ -53.939003   -13.778999  -123.68     ]]

  [[ 151.061       73.221      -19.68     ]
   [ 148.061       77.221        4.3199997]
   [ 151.061       87.221      -10.68     ]
   ...
   [ -59.939003   -25.779     -123.68     ]
   [ -58.939003   -24.779     -123.68     ]
   [ -54.939003   -12.778999  -118.68     ]]

  [[ 151.061       73.221      -18.68     ]
   [ 148.061       71.221      -23.68     ]
   [ 120.061       32.221     -114.68     ]
   ...
   [ -60.939003   -19.779     -123.68     ]
   [ -25.939003    -2.7789993 -109.68     ]
   [ -52.939003   -21.779     -123.68     ]]]


 [[[ 149.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]

  [[ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]

  [[ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]

  ...

  [[ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]

  [[ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]

  [[ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   ...
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]
   [ 151.061      138.22101    131.32     ]]]]